FROM postgres:15-alpine

ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=YourStrong@Passw0rd
ENV POSTGRES_DB=EmployeeManagement

COPY init.sql /docker-entrypoint-initdb.d/

RUN chown postgres:postgres /docker-entrypoint-initdb.d/init.sql

EXPOSE 5432